version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  enable-beta-ecosystems: true
  pull-request-branch-name:
    separator: "/"
  auto-merge:
    enable: true
    strategy: "merge"
    dependency-type: "all"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
