services:
  web:
    cpus: "0.5"  # Works outside Swarm
    image: dmcnally/common-ruby:development-${APP_VERSION}
    command: sleep infinity
    volumes:
      - .:/app
      - rubygems:/rubygems
    ports:
      - '3000:3000'
      - '5900:5901'
    environment: &environment
      DEVELOPMENT_DATABASE_URL: 'postgres://postgres:@postgres:5432/tournament_manager_2_development'
      TEST_DATABASE_URL: 'postgres://postgres:@postgres:5432/tournament_manager_2_test'
      DATABASE_URL: 'postgres://postgres:@postgres:5432/tournament_manager_2_development'
      REDIS_URL: 'redis://redis:6379'
      ENCRYPT_SECRET_KEY: 'QRDUGL+6BlKart8/U4o2kMiHpPgAoNrEIPX1KKVaR1c='
      ENCRYPT_IV: 'gwYE42O06SriGPeX'
      ENCRYPT_SALT: 'P2HuKHAOHzqK6kHn9+Py/8Qt2E9Q1rMojhb2Z27Ul15L5DKzIwD4aElYiz1xhqb+ZdifYiVrkffgnQnfaxHBcrNzS7kUQHbBtPhRGgCTOdsNQzPhBrVvAUe9Ms5B6bFIFL1DdTczJEtOr8s13s6gcKnJHdEP5T7lsn1421hm35Y='
      PARALLEL_PROCESSOR_COUNT: ${PARALLEL_PROCESSOR_COUNT}
      APPLICATION_NAME: Aka Ao
      DOMAIN_NAME: localhost:3000
      NOTIFICATION_EMAILS_SENDER: notifications@localhost.dev
      # FEATURE_INVITE: true
      # TEST_APP_HOST: web
      # TEST_APP_PORT: 3005
      # SELENIUM_HOST: selenium
      # HOLDING_PAGE: true
    env_file:
      - .env
    depends_on:
      assets:
        condition: service_started
      postgres:
        condition: service_healthy
      # elasticsearch:
      #   condition: service_healthy
      mailcatcher:
        condition: service_started
    tty: true
    stdin_open: true
    pid: host

  assets:
    image: dmcnally/tournament-manager:development-${APP_VERSION}
    command: rake dartsass:watch
    volumes:
      - .:/app
      - rubygems:/rubygems
    env_file:
      - .env
    environment: *environment

  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '9876:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", '--username=postgres' ]
      interval: 1s
      timeout: 5s
      retries: 5

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1025'
      - '1080:1080'
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:1080 || exit 1" ]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  es-data:
  rubygems:
