---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "brello.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
type: Opaque
data:
  password: {{ .Values.secrets.postgresql.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "brello.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
type: Opaque
data:
  rails-master-key: {{ .Values.secrets.rails.masterKey }}
  encrypt-secret-key: {{ .Values.secrets.rails.encryptSecretKey }}
  encrypt-iv: {{ .Values.secrets.rails.encryptIv }}
  encrypt-salt: {{ .Values.secrets.rails.encryptSalt }} 