apiVersion: v2
name: brello
description: A Helm chart for Brello Rails application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - rails
  - postgresql
  - kanban
home: https://github.com/yourusername/brello
sources:
  - https://github.com/yourusername/brello
maintainers:
  - name: Your Name
    email: your.email@example.com 